name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add additional steps for testing or other checks

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            cd ~/blog
            git pull
            rm -rf venv
            python3.12 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt

            # Nginx configuration
            sudo cp nginx.conf /etc/nginx/sites-available/blog
            sudo ln -sf /etc/nginx/sites-available/blog /etc/nginx/sites-enabled/
            sudo systemctl reload nginx

            # Systemd service
            sudo cp blog.service /etc/systemd/system/
            sudo systemctl daemon-reload
            sudo systemctl restart blog

            systemctl restart blog
