name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            set -euxo pipefail

            # Update the blog repo
            cd /home/bloguser/blog
            git fetch origin master
            git reset --hard origin/master

            # Update virtual environment dependencies (without recreating)
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # Update static files for nginx
            sudo mkdir -p /var/www/blog
            sudo rsync -a --delete /home/bloguser/blog/static/ /var/www/blog/static/

            # Ensure nginx configuration is current
            sudo cp /home/bloguser/blog/nginx.conf /etc/nginx/sites-available/blog
            sudo ln -sf /etc/nginx/sites-available/blog /etc/nginx/sites-enabled/blog
            sudo nginx -t && sudo systemctl reload nginx

            # Update systemd service and restart blog
            sudo cp /home/bloguser/blog/blog.service /etc/systemd/system/blog.service
            sudo systemctl daemon-reload
            sudo systemctl restart blog

